apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-example
  labels:
    app: web
    name: front-end
spec:
 template:
  metadata:
     name: pod-set
     labels:
       app: web
       name: front-end
  spec:
    containers:
    - image: jenkins
      name:  jenkins-image
 replicas: 6
 selector:
   matchLabels:
     app: web
     name: front-end

