apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-example
  namespace: prod
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: "2Gi"
    limits.cpu: "5"
    limits.memory: "2Gi"