apiVersion: v1
kind: Binding
metadata:
  name: nginx
target:
  apiVersion: v1
  kind: Node
  name: ip-172-31-45-36


  # syntax to apply for this 
  # $ curl --header "context-type:application/json" --request POST --data {"apiVersion":"v1","kind":"Binding"} http://$SERVER/api/v1/namespace/default/pods/$PODNAME/binding/