apiVersion: v1
kind: Service
metadata:
  name: my-nodeport
  labels:
    app: web
spec:
 type: NodePort
 ports:
   - targetPort: 80
     port: 80
     nodePort: 30008
 selector:  # pod labels
  app: web
