apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    name: post
    type: red-ser
spec:
  type: 
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-db
    name: database
    

