apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    name: red
    type: load
spec:
  type: 
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-ser
    name: server
    
