apiVersion: v1
kind: Service
metadata:
  name: result-app
  labels:
    app: res
    type: result-server
spec:
  type: LoadBalancer
  Ports:
    - port: 80
      targetPort: 80
  selector:
    app: result-app
    name: result
