apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    app: web
    type: fron-end
spec:
  template:
    metadata:
      name: my-pod
      labels:
        app: web
        type: fron-end

    spec:
      containers:
        - name: image
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: web
      type: fron-end