apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: web
    type: front-end
spec:
  containers:
    - name:  image
      image: nginx
      env:
      - name: POSTGRES_PASSWORD
        value: secretkey

    